name: Docker Build and Publish Image CI

on:
  push:
    branches: [ "build-and-publish" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: asouchereau/lemmy

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Get short commit SHA
      id: get_sha
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build . -f docker/Dockerfile --build-arg RUST_RELEASE_MODE=release -t "lemmy:${COMMIT_SHA}" -t "lemmy:latest"

    - name: Push image to GHCR
      run: docker push $REGISTRY/$IMAGE_NAME --all-tags
